development:
  adapter: mysql
  database: tigerevents_dev
  host: localhost
  socket: /var/lib/mysql/mysql.sock
  username: tigerevents
  password: tigerevents

test:
  adapter: mysql
  database: tigerevents_test
  host: localhost
  socket: /var/lib/mysql/mysql.sock
  username: tigerevents
  password: tigerevents

production:
  adapter: mysql
  database: tigerevents
  socket: /var/lib/mysql/mysql.sock
  host: localhost
  username: tigerevents
  password: tigerevents
