-- This file is autogenerated by the Rail schema generator, using
-- the schema defined in db/migration/*.rb
--
-- Do not edit this file.  Instead, add a new migration using
-- ./script/generate migration <name>, and then run
-- ./script/generate schema

-- tables 

DROP TABLE activities;
CREATE TABLE activities (
  id serial primary key,
  action character varying(100) NOT NULL DEFAULT '',
  user_id integer NOT NULL DEFAULT 0,
  event_id integer NOT NULL DEFAULT 0,
  created_on timestamp,
  updated_on timestamp
);

DROP TABLE association_types;
CREATE TABLE association_types (
  id serial primary key,
  name character varying(10) NOT NULL DEFAULT ''
);

DROP TABLE bookmarks;
CREATE TABLE bookmarks (
  id serial primary key,
  user_id integer NOT NULL DEFAULT 0,
  event_id integer NOT NULL DEFAULT 0
);

DROP TABLE categories;
CREATE TABLE categories (
  id serial primary key,
  name character varying(100) NOT NULL DEFAULT '',
  hide boolean NOT NULL DEFAULT 'f',
  created_on timestamp,
  updated_on timestamp,
  created_by integer NOT NULL DEFAULT 0
);

DROP TABLE categories_events;
CREATE TABLE categories_events (
  event_id integer NOT NULL DEFAULT 0,
  category_id integer NOT NULL DEFAULT 0
);

DROP TABLE categories_selectors;
CREATE TABLE categories_selectors (
  selector_id integer NOT NULL DEFAULT 0,
  category_id integer NOT NULL DEFAULT 0,
  association_type_id integer NOT NULL DEFAULT 0
);

DROP TABLE eventratings;
CREATE TABLE eventratings (
  id serial primary key,
  event_id integer NOT NULL DEFAULT 0,
  score integer NOT NULL DEFAULT 0
);

DROP TABLE events;
CREATE TABLE events (
  id serial primary key,
  announcement boolean NOT NULL DEFAULT 'f',
  group_id integer,
  description text NOT NULL DEFAULT '',
  title character varying(100) NOT NULL DEFAULT '',
  startTime timestamp NOT NULL,
  endTime timestamp,
  priority_id integer,
  location character varying(100),
  url character varying(100),
  deleted boolean NOT NULL DEFAULT 'f',
  created_on timestamp,
  updated_on timestamp
);

DROP TABLE group_classes;
CREATE TABLE group_classes (
  id serial primary key,
  name character varying(100) NOT NULL DEFAULT '',
  parent_id integer
);

DROP TABLE group_classes_selectors;
CREATE TABLE group_classes_selectors (
  selector_id integer NOT NULL DEFAULT 0,
  group_class_id integer NOT NULL DEFAULT 0,
  association_type_id integer NOT NULL DEFAULT 0
);

DROP TABLE group_classes_users;
CREATE TABLE group_classes_users (
  user_id integer NOT NULL DEFAULT 0,
  group_class_id integer NOT NULL DEFAULT 0
);

DROP TABLE groups;
CREATE TABLE groups (
  id serial primary key,
  name character varying(100) NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  group_class_id integer,
  approved boolean NOT NULL DEFAULT 'f'
);

DROP TABLE groups_selectors;
CREATE TABLE groups_selectors (
  selector_id integer NOT NULL DEFAULT 0,
  group_id integer NOT NULL DEFAULT 0,
  association_type_id integer NOT NULL DEFAULT 0
);

DROP TABLE groups_users;
CREATE TABLE groups_users (
  user_id integer NOT NULL DEFAULT 0,
  group_id integer NOT NULL DEFAULT 0,
  authorized boolean NOT NULL DEFAULT 'f'
);

DROP TABLE layouts;
CREATE TABLE layouts (
  id serial primary key,
  user_id integer
);

DROP TABLE layouts_selectors;
CREATE TABLE layouts_selectors (
  layout_id integer NOT NULL DEFAULT 0,
  selector_id integer NOT NULL DEFAULT 0,
  rank integer NOT NULL DEFAULT 0
);

DROP TABLE priorities;
CREATE TABLE priorities (
  id serial primary key,
  name character varying(30) NOT NULL DEFAULT '',
  rank integer NOT NULL DEFAULT 0
);

DROP TABLE priorities_selectors;
CREATE TABLE priorities_selectors (
  selector_id integer NOT NULL DEFAULT 0,
  priority_id integer NOT NULL DEFAULT 0,
  association_type_id integer NOT NULL DEFAULT 0
);

DROP TABLE selectors;
CREATE TABLE selectors (
  id serial primary key,
  name character varying(100) NOT NULL DEFAULT '',
  label character varying(100) NOT NULL DEFAULT '',
  include_events boolean NOT NULL DEFAULT 'f',
  include_announcements boolean NOT NULL DEFAULT 'f'
);

DROP TABLE users;
CREATE TABLE users (
  id serial primary key,
  login character varying(80) NOT NULL DEFAULT '',
  fullname character varying(80) NOT NULL DEFAULT '',
  email character varying(100) NOT NULL DEFAULT '',
  hashed_pass character varying(40),
  banned boolean NOT NULL DEFAULT 'f',
  superuser boolean NOT NULL DEFAULT 'f',
  created_on timestamp,
  updated_on timestamp
);


-- indexes 

CREATE  INDEX groups_name_index ON groups (name);
CREATE  INDEX users_login_index ON users (login);

-- schema version meta-info 

CREATE TABLE schema_info (
  version integer
);

insert into schema_info (version) values (1);
