-- This file is autogenerated by the Rail schema generator, using
-- the schema defined in db/migration/*.rb
--
-- Do not edit this file.  Instead, add a new migration using
-- ./script/generate migration <name>, and then run
-- ./script/generate schema

-- tables 

DROP TABLE activities;
CREATE TABLE activities (
  id INTEGER PRIMARY KEY NOT NULL,
  action varchar(100) NOT NULL DEFAULT '',
  user_id integer NOT NULL DEFAULT 0,
  event_id integer NOT NULL DEFAULT 0,
  created_on datetime,
  updated_on datetime
);

DROP TABLE association_types;
CREATE TABLE association_types (
  id INTEGER PRIMARY KEY NOT NULL,
  name varchar(10) NOT NULL DEFAULT ''
);

DROP TABLE bookmarks;
CREATE TABLE bookmarks (
  id INTEGER PRIMARY KEY NOT NULL,
  user_id integer NOT NULL DEFAULT 0,
  event_id integer NOT NULL DEFAULT 0
);

DROP TABLE categories;
CREATE TABLE categories (
  id INTEGER PRIMARY KEY NOT NULL,
  name varchar(100) NOT NULL DEFAULT '',
  hide boolean NOT NULL DEFAULT 'f',
  created_on datetime,
  updated_on datetime,
  created_by integer NOT NULL DEFAULT 0
);

DROP TABLE categories_events;
CREATE TABLE categories_events (
  event_id integer NOT NULL DEFAULT 0,
  category_id integer NOT NULL DEFAULT 0
);

DROP TABLE categories_selectors;
CREATE TABLE categories_selectors (
  selector_id integer NOT NULL DEFAULT 0,
  category_id integer NOT NULL DEFAULT 0,
  association_type_id integer NOT NULL DEFAULT 0
);

DROP TABLE eventratings;
CREATE TABLE eventratings (
  id INTEGER PRIMARY KEY NOT NULL,
  event_id integer NOT NULL DEFAULT 0,
  score integer NOT NULL DEFAULT 0
);

DROP TABLE events;
CREATE TABLE events (
  id INTEGER PRIMARY KEY NOT NULL,
  announcement boolean NOT NULL DEFAULT 'f',
  group_id integer,
  description text NOT NULL DEFAULT '',
  title varchar(100) NOT NULL DEFAULT '',
  startTime datetime NOT NULL,
  endTime datetime,
  priority_id integer,
  location varchar(100),
  url varchar(100),
  deleted boolean NOT NULL DEFAULT 'f',
  created_on datetime,
  updated_on datetime
);

DROP TABLE group_classes;
CREATE TABLE group_classes (
  id INTEGER PRIMARY KEY NOT NULL,
  name varchar(100) NOT NULL DEFAULT '',
  parent_id integer
);

DROP TABLE group_classes_selectors;
CREATE TABLE group_classes_selectors (
  selector_id integer NOT NULL DEFAULT 0,
  group_class_id integer NOT NULL DEFAULT 0,
  association_type_id integer NOT NULL DEFAULT 0
);

DROP TABLE group_classes_users;
CREATE TABLE group_classes_users (
  user_id integer NOT NULL DEFAULT 0,
  group_class_id integer NOT NULL DEFAULT 0
);

DROP TABLE groups;
CREATE TABLE groups (
  id INTEGER PRIMARY KEY NOT NULL,
  name varchar(100) NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  group_class_id integer,
  approved boolean NOT NULL DEFAULT 'f'
);

DROP TABLE groups_selectors;
CREATE TABLE groups_selectors (
  selector_id integer NOT NULL DEFAULT 0,
  group_id integer NOT NULL DEFAULT 0,
  association_type_id integer NOT NULL DEFAULT 0
);

DROP TABLE groups_users;
CREATE TABLE groups_users (
  user_id integer NOT NULL DEFAULT 0,
  group_id integer NOT NULL DEFAULT 0,
  authorized boolean NOT NULL DEFAULT 'f'
);

DROP TABLE layouts;
CREATE TABLE layouts (
  id INTEGER PRIMARY KEY NOT NULL,
  user_id integer
);

DROP TABLE layouts_selectors;
CREATE TABLE layouts_selectors (
  layout_id integer NOT NULL DEFAULT 0,
  selector_id integer NOT NULL DEFAULT 0,
  rank integer NOT NULL DEFAULT 0
);

DROP TABLE priorities;
CREATE TABLE priorities (
  id INTEGER PRIMARY KEY NOT NULL,
  name varchar(30) NOT NULL DEFAULT '',
  rank integer NOT NULL DEFAULT 0
);

DROP TABLE priorities_selectors;
CREATE TABLE priorities_selectors (
  selector_id integer NOT NULL DEFAULT 0,
  priority_id integer NOT NULL DEFAULT 0,
  association_type_id integer NOT NULL DEFAULT 0
);

DROP TABLE selectors;
CREATE TABLE selectors (
  id INTEGER PRIMARY KEY NOT NULL,
  name varchar(100) NOT NULL DEFAULT '',
  label varchar(100) NOT NULL DEFAULT '',
  include_events boolean NOT NULL DEFAULT 'f',
  include_announcements boolean NOT NULL DEFAULT 'f'
);

DROP TABLE users;
CREATE TABLE users (
  id INTEGER PRIMARY KEY NOT NULL,
  login varchar(80) NOT NULL DEFAULT '',
  fullname varchar(80) NOT NULL DEFAULT '',
  email varchar(100) NOT NULL DEFAULT '',
  hashed_pass varchar(40),
  banned boolean NOT NULL DEFAULT 'f',
  superuser boolean NOT NULL DEFAULT 'f',
  created_on datetime,
  updated_on datetime
);


-- indexes 

CREATE  INDEX groups_name_index ON groups (name);
CREATE  INDEX users_login_index ON users (login);

-- schema version meta-info 

CREATE TABLE schema_info (
  version integer
);

insert into schema_info (version) values (1);
