-- This file is autogenerated by the Rail schema generator, using
-- the schema defined in db/migration/*.rb
--
-- Do not edit this file.  Instead, add a new migration using
-- ./script/generate migration <name>, and then run
-- ./script/generate schema

-- tables 

DROP TABLE activities;
CREATE TABLE activities (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  action varchar(100) NOT NULL DEFAULT '',
  user_id int(11) NOT NULL DEFAULT 0,
  event_id int(11) NOT NULL DEFAULT 0,
  created_on datetime,
  updated_on datetime
) ENGINE=InnoDB;

DROP TABLE association_types;
CREATE TABLE association_types (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(10) NOT NULL DEFAULT ''
) ENGINE=InnoDB;

DROP TABLE bookmarks;
CREATE TABLE bookmarks (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  user_id int(11) NOT NULL DEFAULT 0,
  event_id int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE categories;
CREATE TABLE categories (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(100) NOT NULL DEFAULT '',
  hide tinyint(1) NOT NULL DEFAULT 0,
  created_on datetime,
  updated_on datetime,
  created_by int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE categories_events;
CREATE TABLE categories_events (
  event_id int(11) NOT NULL DEFAULT 0,
  category_id int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE categories_selectors;
CREATE TABLE categories_selectors (
  selector_id int(11) NOT NULL DEFAULT 0,
  category_id int(11) NOT NULL DEFAULT 0,
  association_type_id int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE eventratings;
CREATE TABLE eventratings (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  event_id int(11) NOT NULL DEFAULT 0,
  score int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE events;
CREATE TABLE events (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  announcement tinyint(1) NOT NULL DEFAULT 0,
  group_id int(11),
  description text NOT NULL DEFAULT '',
  title varchar(100) NOT NULL DEFAULT '',
  startTime datetime NOT NULL,
  endTime datetime,
  priority_id int(11),
  location varchar(100),
  url varchar(100),
  deleted tinyint(1) NOT NULL DEFAULT 0,
  created_on datetime,
  updated_on datetime
) ENGINE=InnoDB;

DROP TABLE group_classes;
CREATE TABLE group_classes (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(100) NOT NULL DEFAULT '',
  parent_id int(11)
) ENGINE=InnoDB;

DROP TABLE group_classes_selectors;
CREATE TABLE group_classes_selectors (
  selector_id int(11) NOT NULL DEFAULT 0,
  group_class_id int(11) NOT NULL DEFAULT 0,
  association_type_id int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE group_classes_users;
CREATE TABLE group_classes_users (
  user_id int(11) NOT NULL DEFAULT 0,
  group_class_id int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE groups;
CREATE TABLE groups (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(100) NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  group_class_id int(11),
  approved tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE groups_selectors;
CREATE TABLE groups_selectors (
  selector_id int(11) NOT NULL DEFAULT 0,
  group_id int(11) NOT NULL DEFAULT 0,
  association_type_id int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE groups_users;
CREATE TABLE groups_users (
  user_id int(11) NOT NULL DEFAULT 0,
  group_id int(11) NOT NULL DEFAULT 0,
  authorized tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE layouts;
CREATE TABLE layouts (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  user_id int(11)
) ENGINE=InnoDB;

DROP TABLE layouts_selectors;
CREATE TABLE layouts_selectors (
  layout_id int(11) NOT NULL DEFAULT 0,
  selector_id int(11) NOT NULL DEFAULT 0,
  rank int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE priorities;
CREATE TABLE priorities (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(30) NOT NULL DEFAULT '',
  rank int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE priorities_selectors;
CREATE TABLE priorities_selectors (
  selector_id int(11) NOT NULL DEFAULT 0,
  priority_id int(11) NOT NULL DEFAULT 0,
  association_type_id int(11) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE selectors;
CREATE TABLE selectors (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  name varchar(100) NOT NULL DEFAULT '',
  label varchar(100) NOT NULL DEFAULT '',
  include_events tinyint(1) NOT NULL DEFAULT 0,
  include_announcements tinyint(1) NOT NULL DEFAULT 0
) ENGINE=InnoDB;

DROP TABLE users;
CREATE TABLE users (
  id int(11) DEFAULT NULL auto_increment PRIMARY KEY,
  login varchar(80) NOT NULL DEFAULT '',
  fullname varchar(80) NOT NULL DEFAULT '',
  email varchar(100) NOT NULL DEFAULT '',
  hashed_pass varchar(40),
  banned tinyint(1) NOT NULL DEFAULT 0,
  superuser tinyint(1) NOT NULL DEFAULT 0,
  created_on datetime,
  updated_on datetime
) ENGINE=InnoDB;


-- indexes 

CREATE  INDEX groups_name_index ON groups (name);
CREATE  INDEX users_login_index ON users (login);

-- schema version meta-info 

DROP TABLE schema_info;
CREATE TABLE schema_info (
  version int(11)
) ENGINE=InnoDB;

insert into schema_info (version) values (1);
