# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

class EventLocationField < ActiveRecord::Migration
  def self.up
    add_column :events, :location, :string, :limit => 100
  end

  def self.down
    remove_column :events, :location
  end
end
